name: RPE_Spleef
version: 1.0.0
api: 1.8.0
main: Jaydenb132\Spleef
author: Jaydenb132
description: The RektPE Spleef Plugin
commands:
  s:
    description: The RektPE Spleef Plugin
    permission: spleef.command
permissions:
  spleef.command:
    default: true
    description: "The RektPE Spleef Plugin"
    children:
      s.join:
        description: "Join The Spleef Arena"
        default: true
      s.help:
        description: "Commands For RPE SPleef"
        default: true
      s.leave:
        description: "Leave The Spleef Arena"
        default: true
      s.stop:
        description: "Stop The Spleef Game"
        default: false
      s.kick:
        description: "Kicks A Player From The Arena"
        default: false
